---
- hosts: all
  become: yes

  tasks:
    # Docker Installation for Ubuntu/Debian
    - name: Install Docker (Ubuntu/Debian)
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    # Docker Installation for Amazon Linux 2
    - name: Install Docker (Amazon Linux 2)
      yum:
        name: docker
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    # Only needed on Ubuntu/Debian:
    - name: Install python3-pip (Ubuntu/Debian)
      apt:
        name: python3-pip
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install python3-docker (Ubuntu/Debian)
      pip:
        name: docker
        executable: pip3
      when: ansible_os_family == "Debian"

    # Amazon Linux: python3/pip3 already installed; just install docker module
    - name: Install docker python module (Amazon Linux)
      pip:
        name: docker
        executable: pip3
      when: ansible_os_family == "RedHat"

    # Ensure community.docker collection is present (for Ansible >=2.9)
    - name: Ensure community.docker is present (Debian 12+)
      ansible.builtin.ansible_galaxy:
        name: community.docker
        type: collection
      when: ansible_os_family == "Debian"

    # Login to DockerHub
    - name: Login to DockerHub
      community.docker.docker_login:
        username: "{{ docker_hub_user }}"
        password: "{{ docker_hub_pass }}"
      vars:
        docker_hub_user: "sarojnayak1983"
        docker_hub_pass: "{{ lookup('env', 'DOCKERHUB_PASS') }}"

    # Stop previous container
    - name: Stop previous container if running
      community.docker.docker_container:
        name: bankpro-app
        state: stopped
        timeout: 30
      ignore_errors: yes

    # Remove old image
    - name: Remove old bankpro image (if any)
      community.docker.docker_image:
        name: sarojnayak1983/bankpro
        state: absent

    # Pull latest image
    - name: Pull image
      community.docker.docker_image:
        name: sarojnayak1983/bankpro
        tag: latest
        source: pull
        state: present

    # Run container
    - name: Run container
      community.docker.docker_container:
        name: bankpro-app
        image: sarojnayak1983/bankpro:latest
        state: started
        restart_policy: always
        ports:
          - "8080:8080"

    # Print running containers
    - name: Print running containers
      community.docker.docker_container_info:
        name: bankpro-app
      register: containers_info

    - name: Show running containers output
      debug:
        var: containers_info
